#!/usr/bin/env bash

# Find the process ID (PID) of the '4-to_infinity_and_beyond' script
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -n "$pid" ]; then
    # Use kill to stop the process gracefully
    kill "$pid"
    echo echo "Terminated"
else
    echo "Not running"
fi
