#!/usr/bin/env bash
# This script displays the content of a file /etc/passwd.

# assign the file name to a variable
file="/etc/passwd"

# open the file
exec 3<"$file"

# use a loop to read the file
# while the file is open, read each line
while IFS=: read -r username _ userid _ _ homedir _
do
    # display the required information
    echo "$username"
    echo "$userid"
    echo "$homedir"
done <&3

# close the file
exec 3<&-
