#!/usr/bin/env bash
# This script displays the content of a file /etc/passwd.

# assign the file name to a variable
file="/etc/passwd"

# open the file
exec 3<"$file"

# use a loop to read the file
# while the file is open, read each line
while IFS=: read -r username password userid groupid _ homedir shell
do
    # display the required information
    echo "The user $username is part of the $groupid gang, lives in $homedir, and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $username"
done <&3

# close the file
exec 3<&-
