#!/usr/bin/env bash
# This script displays some text

counter=1

while [[ counter -le 20 ]]; do
    echo $counter
    ((counter++))
    case $counter in
	"5")
	    echo "bad luck from China"
	    ;;
	"10")
	    echo "bad luck from Japan"
	    ;;
	"18")
	    echo "bad luck from Italy"
	    ;;
    esac
done
