#!/usr/bin/env bash
# This script is displaying information.

filename="school"

if [[ -e "$filename" ]]
then
    echo "school file exists"
    if [[ -f "$filename" ]]
    then
	echo "school is a regular file"
	if [[ -s "$filename" ]]
	then
	    echo "school file is not empty"
	else
	    echo "school file is empty"
	fi
    fi
else
    echo "school file does not exist"
fi
