#!/usr/bin/env bash
# Script displays all active IPv4 IPs on the machine.

# Get the active IPv4 IPs
ips=$(ip -4 addr show | grep inet | awk '{print $2}' | cut -d'/' -f1)

# Display the IPs
echo "$ips"
